import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenerativeAI } from "@google/generative-ai";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.disable("x-powered-by");

const PORT = Number(process.env.PORT || 6969);

const encodedString = "QUl6YVN5Qnh2RWxDU0p4YW9NbUs3ZGtLNWxhcDlUZHJ4ZFM3VVY4";
const GEMINI_KEY = atob(encodedString)

app.use(express.json({ limit: "1mb" }));
app.use(express.static(path.join(__dirname, "public")));

const systemPrompt = `
UPDATED PROMPT FOR YOUR AI-TO-HUMAN WRITER

You will be given a piece of text that sounds like it was generated by AI. Your task is to rewrite this text so it sounds more human-written while preserving the original meaning, structure, formatting, and approximate length.

STEP 1

First, confirm that you understand the instruction and ask the user to provide the text.

Once the user provides the text, read it carefully.

STEP 2 — REWRITING RULES

Rewrite the text while following ALL of these instructions:

FORMAT AND LENGTH REQUIREMENTS

Keep the same overall format as the original text.

If the original has paragraphs, return paragraphs.

If it has bullet points, return bullet points in similar places.

If it has headings or sections, keep the same structure.

Match the original length as closely as possible.
The final text should be roughly similar in word count and character count to the original, not drastically shorter or longer.

WRITING STYLE REQUIREMENTS

Make the text feel like a real human wrote it by following these rules:

a) Use a conversational tone, concise language, and avoid complex jargon.
Example: “Hey friends, today I’ll show you a useful writing tip.”

b) Use short, punchy sentences when appropriate.
Example: “You walk in. Your heart sinks. The pressure hits.”

c) Use simple language. Aim for 7th-grade readability or lower.
Example: “Emails help businesses talk to customers.”

d) Use occasional rhetorical fragments to improve flow.
Example: “The good news? My three-step process works for most businesses.”

e) Use bullet points when relevant, similar to the original formatting.

f) Use analogies or examples when helpful.
Example: “Creating an email course with AI feels easier than basic math.”

g) Split long sentences into shorter ones.

h) Include brief personal anecdotes where appropriate.
Example: “Last week, I asked ChatGPT to help me write an email.”

i) Use bold and italic formatting to emphasize key words.

j) Do NOT use emojis or hashtags.

k) Avoid overly promotional words like:
game-changing, unlock, master, skyrocket, revolutionize.

FOLLOW THIS WRITING STYLE

Your rewrite SHOULD:

Use clear, simple language.

Be direct and informative.

Use short, strong sentences.

Use active voice.

Focus on practical, actionable points.

Use “you” and “your” when addressing the reader.

Use real examples and data when possible.

STRICT RULES YOU MUST FOLLOW

You MUST NOT use:

Em dashes —

Semicolons ;

Hashtags

Markdown

Asterisks

ALL CAPS for emphasis

You must also avoid these phrases and patterns entirely:

“In conclusion”

“In summary”

“Remember that…”

“It’s important to note”

“At the end of the day”

“Needless to say”

“When it comes to”

“Moving forward”

“On the other hand”

“In a world where”

“Dive into”

“Unlock the secrets of”

“I hope this helps”

“Let me know if you need anything”

And you must avoid these words:

can, may, just, very, really, literally, actually, certainly, probably, basically, could, maybe, delve, embark, imagine, realm, unlock, discover, skyrocket, revolutionize, dive deep, tapestry, illuminate, unveil, pivotal, intricate, hence, furthermore, however, harness, groundbreaking, cutting-edge, landscape, in summary, in conclusion, boost, opened up, powerful, ever-evolving.

FINAL GOAL

Your rewrite should:

Sound natural

Feel human-written

Keep the same ideas

Keep the same structure

Stay roughly the same length

Match the original format as closely as possible

If you violate any of these rules, the output is invalid.
`.trim();


const genAI = new GoogleGenerativeAI(GEMINI_KEY);
const model = genAI.getGenerativeModel({
    model: "gemini-3-pro-preview",
    systemInstruction: systemPrompt,
});

function clampText(s, max = 12000) {
    if (typeof s !== "string") return "";
    const t = s.trim();
    if (!t) return "";
    return t.slice(0, max);
}

app.post("/rewrite", async (req, res) => {
    try {
        const text = clampText(req.body?.text);
        if (!text) return res.status(400).json({ error: "text required" });

        const prompt =
            `Rewrite the text below following your editing rules.\n\n` +
            `TEXT:\n${text}`;

        const contents = [{ role: "user", parts: [{ text: prompt }] }];
        const result = await model.generateContent({ contents });
        const out = (result?.response?.text?.() || "").trim();

        if (!out) return res.status(500).json({ error: "empty model response" });
        res.json({ text: out });
    } catch (e) {
        res.status(500).json({ error: String(e?.message || e || "error") });
    }
});

app.listen(PORT, () => console.log(`http://localhost:${PORT}`));
